FROM quay.io/ansible/eda-ui:main

COPY tools/docker/nginx/certs/ /etc/nginx/certs/
COPY tools/docker/nginx/my_certs/ /etc/nginx/my_certs/
COPY tools/docker/nginx/default.conf.template /etc/nginx/templates/default.conf.template
