apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eda
      comp: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eda
        comp: postgres
    spec:
      containers:
        - env:
            - name: POSTGRESQL_DATABASE
              value: eda
            - name: POSTGRESQL_USER
              value: eda
            - name: POSTGRESQL_PASSWORD
              value: secret
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: secret
          image: quay.io/sclorg/postgresql-13-c9s:latest
          name: postgres
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
status: {}
