apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-ui
spec:
  selector:
    matchLabels:
      app: eda
      comp: ui
  replicas: 1
  template:
    metadata:
      labels:
        app: eda
        comp: ui
    spec:
      containers:
        - env:
            - name: EDA_PROTOCOL
              value: http
            - name: EDA_HOST
              value: eda-api:8000
            - name: EDA_SERVER
              value: http://eda-api:8000
            - name: EDA_WEBHOOK_SERVER
              value: http://eda-api:8000
          name: eda-ui
          imagePullPolicy: Never
          image: quay.io/ansible/eda-ui:main
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: eda-env-properties
status: {}
