apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    comp: ui
  includeSelectors: true

resources:
- deployment.yaml
- service.yaml

images:
- name: eda-ui
  newName: quay.io/ansible/eda-ui
  newTag: latest
