# Complete documentation with many more options at:
# https://docs.sonarqube.org/latest/analysis/analysis-parameters/

## The unique project identifier. This is mandatory.
# Do not duplicate or reuse!
# Available characters: [a-zA-Z0-9_:\.\-]
# Must have least one non-digit.
# Recommended format: <group>:<project>
sonar.projectKey=ansible_eda-server

sonar.organization=ansible

# Customize what paths to scan. Default is .
sonar.sources=src

# Verbose name of project displayed in WUI. Default is set to the projectKey. This field is optional.
sonar.projectName=eda-server

# Version of project. This field is optional.
#sonar.projectVersion=1.0

# Tell sonar scanner where coverage files exist
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions for analysis
sonar.exclusions=**/migrations/**/*,**/tests/**/*,**/test_*.py,**/*_test.py,tools/**/*,scripts/**/*

# Issue ignoring rules
sonar.issue.ignore.multicriteria=e1,e2
# Ignore "should be a variable" in migrations
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.e1.resourceKey=**/migrations/**/*
# Ignore complexity issues in migrations
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e2.resourceKey=**/migrations/**/*

# Only scan with python3
sonar.python.version=3.11,3.12

# Ignore code duplications for migrations and tests
sonar.cpd.exclusions=**/migrations/*.py,**/tests/**/*,**/test_*.py

# Test exclusions (these paths won't be analyzed for quality issues)
sonar.test.exclusions=tests/**/*,**/test_*.py,**/*_test.py

# Include only Python files for analysis
sonar.inclusions=**/*.py
