apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eda
      comp: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eda
        comp: scheduler
    spec:
      containers:
        - args:
            - /bin/bash
            - -c
            - aap-eda-manage scheduler
          env:
            - name: EDA_DATABASE_URL
              value: postgresql+asyncpg://postgres:secret@postgres/eda
            - name: EDA_DB_HOST
              value: eda-postgres
            - name: EDA_DB_PASSWORD
              value: secret
            - name: EDA_SECRET_KEY
              value: secret
            - name: EDA_MQ_HOST
              value: eda-redis
          envFrom:
          - configMapRef:
              name: eda-env-properties
          image: aap-eda
          imagePullPolicy: Never
          name: eda-scheduler
          resources: {}
      restartPolicy: Always
status: {}
