apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    comp: scheduler
  includeSelectors: true

resources:
- deployment.yaml

images:
- name: aap-eda
  newName: localhost/aap-eda
  newTag: latest
