apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eda
      comp: api
  strategy: {}
  template:
    metadata:
      labels:
        app: eda
        comp: api
    spec:
      serviceAccountName: eda-default-sa
      containers:
        - args:
            - /bin/bash
            - -c
            - >-
              aap-eda-manage migrate
              && ANSIBLE_REVERSE_RESOURCE_SYNC=false aap-eda-manage create_initial_data
              && ANSIBLE_REVERSE_RESOURCE_SYNC=false scripts/create_superuser.sh
              && aap-eda-manage runserver 0.0.0.0:8000
          env:
            - name: EDA_DATABASE_URL
              value: postgresql+asyncpg://postgres:secret@postgres/eda
            - name: EDA_DB_HOST
              value: eda-postgres
            - name: EDA_ACTIVATION_DB_HOST
              value: eda-postgres
            - name: EDA_DB_PASSWORD
              value: secret
            - name: EDA_SECRET_KEY
              value: secret
            - name: EDA_MQ_HOST
              value: eda-redis
            - name: EDA_ALLOWED_HOSTS
              value: "['*']"
            - name: EDA_DEPLOYMENT_TYPE
              value: k8s
          envFrom:
          - configMapRef:
              name: eda-env-properties
          image: aap-eda
          imagePullPolicy: Never
          name: eda-api
          ports:
            - containerPort: 8000
          startupProbe:
            httpGet:
              path: /_healthz
              port: 8000
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /_healthz
              port: 8000
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            periodSeconds: 15
          resources: {}
      restartPolicy: Always
      initContainers:
        - name: wait-for-postgres
          image: postgresql
          command: [ 'sh', '-c', "until pg_isready -h eda-postgres -p 5432; do echo waiting for eda-postgres; sleep 2; done" ]
status: {}
