apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eda-default-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eda-default-job
subjects:
- kind: ServiceAccount
  name: eda-default-sa
  namespace: aap-eda
