# Generated by Django 4.0.8 on 2022-11-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('execution_environment', models.TextField()),
                ('working_directory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlembicVersion',
            fields=[
                ('version_num', models.AutoField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='JobInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='JobInstanceEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_uuid', models.UUIDField()),
                ('counter', models.IntegerField()),
                ('stdout', models.TextField()),
                ('type', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JobInstanceHost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.TextField()),
                ('job_uuid', models.UUIDField()),
                ('playbook', models.TextField()),
                ('play', models.TextField()),
                ('task', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('git_hash', models.TextField()),
                ('url', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rulebook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('rulesets', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.TextField(max_length=320)),
                ('hashed_password', models.TextField(max_length=1024)),
                ('is_active', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('is_verified', models.BooleanField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('rulebook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.rulebook')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('action', models.JSONField()),
                ('ruleset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.ruleset')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_type', models.TextField(max_length=13)),
                ('action', models.TextField(max_length=6)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.role')),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('playbook', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.project')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('inventory', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.project')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraVar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('extra_var', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.project')),
            ],
        ),
        migrations.CreateModel(
            name='AuditRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('status', models.TextField()),
                ('fired_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('definition', models.JSONField()),
                ('activation_instance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.activationinstance')),
                ('job_instance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.jobinstance')),
                ('rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.rule')),
                ('ruleset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.ruleset')),
            ],
        ),
        migrations.CreateModel(
            name='ActivationInstanceLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_number', models.IntegerField()),
                ('log', models.TextField()),
                ('activation_instance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.activationinstance')),
            ],
        ),
        migrations.CreateModel(
            name='ActivationInstanceJobInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activation_instance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.activationinstance')),
                ('job_instance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.jobinstance')),
            ],
        ),
        migrations.AddField(
            model_name='activationinstance',
            name='extra_var_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.extravar'),
        ),
        migrations.AddField(
            model_name='activationinstance',
            name='inventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.inventory'),
        ),
        migrations.AddField(
            model_name='activationinstance',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.project'),
        ),
        migrations.AddField(
            model_name='activationinstance',
            name='rulebook_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.rulebook'),
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('status', models.TextField()),
                ('is_enabled', models.BooleanField()),
                ('restarted_at', models.DateTimeField()),
                ('restart_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('working_directory', models.TextField()),
                ('execution_environment', models.TextField(max_length=6)),
                ('restart_policy', models.TextField(max_length=10)),
                ('extra_var_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.extravar')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.inventory')),
                ('rulebook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.rulebook')),
            ],
        ),
    ]
