# Generated by Django 4.0.8 on 2022-11-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlembicVersion',
        ),
    ]
