# Generated by Django 4.0.8 on 2022-12-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0002_delete_alembicversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationinstance',
            name='activation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='eda.activation'),
            preserve_default=False,
        ),
    ]
