# Generated by Django 4.1.4 on 2022-12-23 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("git_hash", models.TextField()),
                ("url", models.TextField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("modified_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Playbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("playbook", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtraVar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("extra_var", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE core_extravar ADD CONSTRAINT fk_core_project
                FOREIGN KEY (project_id) REFERENCES core_project (id)
                ON DELETE CASCADE
                """,
                """
                ALTER TABLE core_playbook ADD CONSTRAINT fk_core_project
                FOREIGN KEY (project_id) REFERENCES core_project (id)
                ON DELETE CASCADE
                """,
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
