# Generated by Django 4.1.5 on 2023-01-24 18:18

from django.db import migrations

from aap_eda.core.db_utils.large_object_triggers import (
    create_large_object_trigger_func_sql,
    drop_create_large_object_func_sql,
    delete_large_object_trigger_func_sql,
    drop_delete_large_object_func_sql,
    apply_large_object_triggers,
    unapply_large_object_triggers,
)


def create_triggers(apps, schema_editor):
    apply_large_object_triggers(schema_editor.connection)


def drop_triggers(apps, schema_editor):
    unapply_large_object_triggers(schema_editor.connection)


class Migration(migrations.Migration):

    dependencies = [("core", "0002_aap_eda_model_init")]

    operations = [
        migrations.RunSQL(
            create_large_object_trigger_func_sql(),
            reverse_sql=drop_create_large_object_func_sql(),
        ),
        migrations.RunSQL(
            delete_large_object_trigger_func_sql(),
            reverse_sql=drop_delete_large_object_func_sql(),
        ),
        migrations.RunPython(
            create_triggers, reverse_code=drop_triggers
        ),
    ]
