# Generated by Django 3.2.18 on 2023-06-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.TextField(
                error_messages={"unique": "A project with this name already exists."},
                unique=True,
            ),
        ),
    ]
