# Generated by Django 4.1.5 on 2023-01-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_aap_eda_model_init"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rulebook",
            name="rulesets",
            field=models.TextField(default=""),
        ),
    ]
