# Generated by Django 4.1.5 on 2023-01-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_rulebook_rulesets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
