# Generated by Django 3.2.18 on 2023-08-02 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_project_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={"ordering": ("-received_at", "-rule_fired_at")},
        ),
    ]
