# Generated by Django 3.2.18 on 2023-08-10 13:29

from django.db import migrations, models

import aap_eda.core.enums


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_auditevent_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="current_job_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="activation",
            name="status",
            field=models.TextField(
                choices=[
                    ("starting", "starting"),
                    ("running", "running"),
                    ("pending", "pending"),
                    ("failed", "failed"),
                    ("stopping", "stopping"),
                    ("stopped", "stopped"),
                    ("deleting", "deleting"),
                    ("completed", "completed"),
                    ("unresponsive", "unresponsive"),
                ],
                default=aap_eda.core.enums.ActivationStatus["PENDING"],
            ),
        ),
        migrations.AlterField(
            model_name="activationinstance",
            name="status",
            field=models.TextField(
                choices=[
                    ("starting", "starting"),
                    ("running", "running"),
                    ("pending", "pending"),
                    ("failed", "failed"),
                    ("stopping", "stopping"),
                    ("stopped", "stopped"),
                    ("deleting", "deleting"),
                    ("completed", "completed"),
                    ("unresponsive", "unresponsive"),
                ],
                default=aap_eda.core.enums.ActivationStatus["PENDING"],
            ),
        ),
    ]
