# Generated by Django 3.2.20 on 2023-08-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_auto_20230810_1329"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="verify_ssl",
            field=models.BooleanField(default=True),
        ),
    ]
