# Generated by Django 3.2.20 on 2023-08-15 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_auto_20230810_1329"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditrule",
            name="definition",
        ),
        migrations.RemoveField(
            model_name="auditrule",
            name="description",
        ),
    ]
