# Generated by Django 4.1.5 on 2023-01-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_activationinstance_ix_act_inst_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extravar",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="playbook",
            name="name",
            field=models.TextField(),
        ),
    ]
