# Generated by Django 4.1.5 on 2023-02-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_activation_restart_policy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activationinstance",
            name="large_data_id",
        ),
        migrations.RemoveField(
            model_name="project",
            name="large_data_id",
        ),
    ]
