# Generated by Django 3.2.20 on 2023-08-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_auto_20230815_1926"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="verify_ssl",
            field=models.BooleanField(default=True),
        ),
    ]
