# Generated by Django 4.1.5 on 2023-02-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_activation_restart_policy_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditrule",
            old_name="rule_id",
            new_name="rule",
        ),
    ]
