# Generated by Django 3.2.20 on 2023-08-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_auto_20230821_1343"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="verify_ssl",
            field=models.BooleanField(default=True),
        ),
    ]
