# Generated by Django 3.2.20 on 2023-08-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_project_verify_ssl"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationinstance",
            name="git_hash",
            field=models.TextField(null=True),
        ),
    ]
