# Generated by Django 4.1.5 on 2023-02-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_project_archive_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditrule",
            old_name="rule_id",
            new_name="rule",
        ),
    ]
