# Generated by Django 3.2.18 on 2023-03-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_rename_rule_id_auditrule_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="import_task_id",
            field=models.UUIDField(null=True, default=None),
        ),
        migrations.AddField(
            model_name="project",
            name="import_state",
            field=models.TextField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                ],
                default="pending",
            ),
        ),
    ]
