# Generated by Django 3.2.18 on 2023-03-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_rename_rule_id_auditrule_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="archive_file_sha256",
            field=models.TextField(default=""),
        ),
    ]
