# Generated by Django 3.2.18 on 2023-03-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20230306_1329"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activation",
            name="working_directory",
        ),
    ]
