# Generated by Django 3.2.18 on 2023-03-15 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_auto_20230306_1329"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField()),
                ("credential_type", models.TextField()),
                ("username", models.TextField(null=True)),
                ("secret", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_credential",
            },
        ),
        migrations.CreateModel(
            name="DecisionEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.TextField(unique=True)),
                ("description", models.TextField()),
                ("registry", models.TextField()),
                ("tag", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.credential",
                    ),
                ),
            ],
            options={
                "db_table": "core_decision_environment",
            },
        ),
        migrations.AddConstraint(
            model_name="credential",
            constraint=models.CheckConstraint(
                check=models.Q(("name", ""), _negated=True),
                name="ck_empty_credential_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="decisionenvironment",
            constraint=models.CheckConstraint(
                check=models.Q(("name", ""), _negated=True),
                name="ck_empty_decision_env_name",
            ),
        ),
    ]
