# Generated by Django 3.2.18 on 2023-03-21 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_awx_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activation",
            name="working_directory",
        ),
    ]
