# Generated by Django 4.2.7 on 2023-11-15 14:08

import django.db.models.deletion
from django.db import migrations, models


# Ensure that the latest_instance field is populated for all existing
# activations after the migration is applied.
def populate_latest_instance(apps, schema_editor):
    Activation = apps.get_model("core", "Activation")  # noqa: N806
    ActivationInstance = apps.get_model(  # noqa: N806
        "core",
        "ActivationInstance",
    )

    for activation in Activation.objects.all():
        latest_instance = (
            ActivationInstance.objects.filter(activation=activation)
            .order_by("-started_at")
            .first()
        )
        if latest_instance:
            activation.latest_instance = latest_instance
            activation.save(update_fields=["latest_instance"])


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("core", "0011_auto_20230922_1431"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="latest_instance",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.activationinstance",
            ),
        ),
        migrations.AddField(
            model_name="activationinstance",
            name="log_read_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name="ActivationRequestQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request",
                    models.TextField(
                        choices=[
                            ("start", "start"),
                            ("stop", "stop"),
                            ("restart", "restart"),
                            ("delete", "delete"),
                            ("auto_start", "auto_start"),
                        ]
                    ),
                ),
                (
                    "activation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.activation",
                    ),
                ),
            ],
            options={
                "db_table": "core_activation_request_queue",
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(
            populate_latest_instance,
            migrations.RunPython.noop,
        ),
    ]
