# Generated by Django 3.2.20 on 2023-10-17 16:11

from django.db import migrations, models
import django.db.models.deletion


def populate_latest_instance(apps, schema_editor):
    Activation = apps.get_model("core", "Activation")  # noqa: N806
    ActivationInstance = apps.get_model(  # noqa: N806
        "core", "ActivationInstance"
    )

    for activation in Activation.objects.all():
        latest_instance = (
            ActivationInstance.objects.filter(activation=activation)
            .order_by("-started_at")
            .first()
        )
        if latest_instance:
            activation.latest_instance = latest_instance
            activation.save(update_fields=["latest_instance"])


def undo_populate_latest_instance(apps, schema_editor):
    migrations.RemoveField(
        model_name="activation",
        name="latest_instance",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_auto_20230922_1431"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="latest_instance",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.activationinstance",
            ),
        ),
        migrations.AddField(
            model_name="activationinstance",
            name="log_read_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(
            populate_latest_instance,
            undo_populate_latest_instance,
        ),
    ]
