# Generated by Django 3.2.18 on 2023-03-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_activation_working_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="rulebook",
            name="path",
            field=models.TextField(default=""),
        ),
    ]
