# Generated by Django 4.2.7 on 2023-12-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_activation_latest_instance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditaction",
            name="status_message",
            field=models.TextField(default=None, null=True),
        ),
    ]
