# Generated by Django 3.2.18 on 2023-10-19 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_auto_20231017_1611"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivationRequestQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request",
                    models.TextField(
                        choices=[
                            ("start", "start"),
                            ("stop", "stop"),
                            ("restart", "restart"),
                            ("delete", "delete"),
                        ]
                    ),
                ),
                (
                    "activation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.activation",
                    ),
                ),
            ],
            options={
                "db_table": "core_activation_request_queue",
                "ordering": ["id"],
            },
        ),
    ]
