# Generated by Django 3.2.18 on 2023-03-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_rulebook_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rulebook",
            name="path",
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name="rulebook",
            unique_together={("project_id", "path", "name")},
        ),
    ]
