# Generated by Django 4.2.7 on 2023-12-19 21:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import aap_eda.core.enums


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auditaction_status_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="resource_type",
            field=models.TextField(
                choices=[
                    ("activation", "activation"),
                    ("activation_instance", "activation_instance"),
                    ("audit_rule", "audit_rule"),
                    ("audit_event", "audit_event"),
                    ("task", "task"),
                    ("user", "user"),
                    ("project", "project"),
                    ("inventory", "inventory"),
                    ("extra_var", "extra_var"),
                    ("rulebook", "rulebook"),
                    ("role", "role"),
                    ("decision_environment", "decision_environment"),
                    ("credential", "credential"),
                    ("source", "source"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("type", models.TextField()),
                ("name", models.TextField(unique=True)),
                ("args", models.JSONField(default=None, null=True)),
                ("listener_args", models.JSONField(default=None, null=True)),
                (
                    "restart_policy",
                    models.TextField(
                        choices=[
                            ("always", "always"),
                            ("on-failure", "on-failure"),
                            ("never", "never"),
                        ],
                        default=aap_eda.core.enums.RestartPolicy["ON_FAILURE"],
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_environment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.decisionenvironment",
                    ),
                ),
                (
                    "listener_activation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.activation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_source",
                "indexes": [
                    models.Index(fields=["id"], name="ix_source_id"),
                    models.Index(fields=["name"], name="ix_source_name"),
                ],
            },
        ),
    ]
