# Generated by Django 3.2.18 on 2023-11-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_activationrequestqueue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationrequestqueue",
            name="request",
            field=models.TextField(
                choices=[
                    ("start", "start"),
                    ("stop", "stop"),
                    ("restart", "restart"),
                    ("delete", "delete"),
                    ("auto_start", "auto_start"),
                ]
            ),
        ),
    ]
