# Generated by Django 4.2.7 on 2024-01-09 16:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auditaction_status_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "activation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.activation",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("type", models.TextField()),
                ("args", models.JSONField(default=None, null=True)),
                ("listener_args", models.JSONField(default=None, null=True)),
            ],
            options={
                "db_table": "core_source",
            },
            bases=("core.activation",),
        ),
        migrations.AlterField(
            model_name="permission",
            name="resource_type",
            field=models.TextField(
                choices=[
                    ("activation", "activation"),
                    ("activation_instance", "activation_instance"),
                    ("audit_rule", "audit_rule"),
                    ("audit_event", "audit_event"),
                    ("task", "task"),
                    ("user", "user"),
                    ("project", "project"),
                    ("inventory", "inventory"),
                    ("extra_var", "extra_var"),
                    ("rulebook", "rulebook"),
                    ("role", "role"),
                    ("decision_environment", "decision_environment"),
                    ("credential", "credential"),
                    ("source", "source"),
                ]
            ),
        ),
    ]
