# Generated by Django 4.2.7 on 2023-12-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_permission_resource_type_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="sources",
            field=models.ManyToManyField(default=None, to="core.source"),
        ),
    ]
