# Generated by Django 4.2.7 on 2024-01-09 22:44

from django.db import migrations

import aap_eda.core.utils.crypto.fields


def populate_empty_secrets(apps, schema_editor):
    Credential = apps.get_model("core", "Credential")  # noqa: N806
    Credential.objects.filter(secret__isnull=True).update(secret="")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_activation_awx_token"),
    ]

    operations = [
        migrations.RunPython(populate_empty_secrets),
        migrations.AlterField(
            model_name="credential",
            name="secret",
            field=aap_eda.core.utils.crypto.fields.EncryptedTextField(),
        ),
    ]
