# Generated by Django 3.2.18 on 2023-03-28 18:18

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_rbac_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=timezone.now()
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
