# Generated by Django 4.2.7 on 2024-01-29 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_credential_secret"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ActivationInstance",
            new_name="RulebookProcess",
        ),
        migrations.AlterModelTable(
            name="rulebookprocess",
            table="core_rulebook_process",
        ),
    ]
