# Generated by Django 3.2.18 on 2023-03-30 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_roles_dates"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField()),
                ("name", models.TextField()),
                ("status", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("fired_at", models.DateTimeField()),
            ],
            options={
                "db_table": "core_audit_action",
            },
        ),
        migrations.RemoveField(
            model_name="auditrule",
            name="rule",
        ),
        migrations.RemoveField(
            model_name="auditrule",
            name="ruleset",
        ),
        migrations.AddField(
            model_name="auditrule",
            name="rule_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="auditrule",
            name="ruleset_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="auditrule",
            name="definition",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="auditrule",
            name="fired_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(null=True)),
                ("source_name", models.TextField()),
                ("source_type", models.TextField()),
                ("received_at", models.DateTimeField()),
                ("payload", models.JSONField(null=True)),
                (
                    "audit_action",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.auditaction",
                    ),
                ),
            ],
            options={
                "db_table": "core_audit_event",
            },
        ),
        migrations.AddField(
            model_name="auditaction",
            name="audit_rule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.auditrule",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="auditaction",
            unique_together={("uuid", "name")},
        ),
    ]
