# Generated by Django 3.2.18 on 2023-04-02 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_roles_dates"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditAction",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("status", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("fired_at", models.DateTimeField()),
            ],
            options={
                "db_table": "core_audit_action",
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("source_name", models.TextField()),
                ("source_type", models.TextField()),
                ("received_at", models.DateTimeField()),
                ("payload", models.JSONField(null=True)),
            ],
            options={
                "db_table": "core_audit_event",
            },
        ),
        migrations.RemoveIndex(
            model_name="auditrule",
            name="ix_audit_rule_fired_date",
        ),
        migrations.RenameField(
            model_name="auditrule",
            old_name="fired_date",
            new_name="fired_at",
        ),
        migrations.RemoveField(
            model_name="auditrule",
            name="rule",
        ),
        migrations.RemoveField(
            model_name="auditrule",
            name="ruleset",
        ),
        migrations.AddField(
            model_name="auditrule",
            name="rule_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="auditrule",
            name="ruleset_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="auditrule",
            name="definition",
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name="auditrule",
            index=models.Index(
                fields=["fired_at"], name="ix_audit_rule_fired_at"
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="audit_actions",
            field=models.ManyToManyField(
                related_name="audit_events", to="core.AuditAction"
            ),
        ),
        migrations.AddField(
            model_name="auditaction",
            name="audit_rule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.auditrule",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="auditaction",
            unique_together={("id", "name")},
        ),
    ]
