# Generated by Django 4.2.7 on 2024-01-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_credential_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationinstancelog",
            name="log_timestamp",
            field=models.BigIntegerField(default=0),
        ),
    ]
