# Generated by Django 4.2.7 on 2024-01-24 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_credential_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationrequestqueue",
            name="instance_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="activationrequestqueue",
            name="related_type",
            field=models.TextField(
                default="aap_eda.core.models.Activation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="activationrequestqueue",
            name="activation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.activation",
            ),
        ),
    ]
