# Generated by Django 3.2.18 on 2023-03-29 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_roles_dates"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(null=True)),
                ("source_name", models.TextField()),
                ("source_type", models.TextField()),
                ("received_at", models.DateTimeField()),
                (
                    "audit_rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.auditrule",
                    ),
                ),
            ],
            options={
                "db_table": "core_audit_event",
            },
        ),
    ]
