# Generated by Django 4.2.7 on 2024-01-29 23:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_rename_activationinstance_rulebookprocess_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ActivationInstanceLog",
            new_name="RulebookProcessLog",
        ),
        migrations.AlterModelTable(
            name="rulebookprocesslog",
            table="core_rulebook_process_log",
        ),
    ]
