# Generated by Django 3.2.18 on 2023-03-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_auto_20230402_0417"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="import_error",
            field=models.TextField(default=None, null=True),
        ),
    ]
