# Generated by Django 4.2.7 on 2024-01-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_auto_20240103_0502"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="listener",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
