# Generated by Django 3.2.18 on 2023-03-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_auto_20230330_2051"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditrule",
            name="ix_audit_rule_fired_date",
        ),
        migrations.RenameField(
            model_name="auditrule",
            old_name="fired_date",
            new_name="fired_at",
        ),
        migrations.AddIndex(
            model_name="auditrule",
            index=models.Index(
                fields=["fired_at"], name="ix_audit_rule_fired_at"
            ),
        ),
    ]
