# Generated by Django 4.2.7 on 2024-01-30 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_activation_credentials_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ActivationInstanceLog",
            new_name="RulebookProcessLog",
        ),
        migrations.AlterModelTable(
            name="rulebookprocesslog",
            table="core_rulebook_process_log",
        ),
    ]
