# Generated by Django 4.2.7 on 2024-01-31 10:49

import django.db.models.deletion
from django.db import migrations, models

from aap_eda.core.utils import get_fully_qualified_name


def populate_parent_fields(apps, schema_editor):
    RulebookProcess = apps.get_model("core", "RulebookProcess")  # noqa: N806
    for instance in RulebookProcess.objects.all():
        if instance.activation is None:
            continue
        if not instance.parent_id:
            instance.parent_id = instance.activation.id
        if not instance.parent_fqcn:
            instance.parent_fqcn = get_fully_qualified_name(
                instance.activation,
            )
        instance.save(update_fields=["parent_id", "parent_fqcn"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0018_rename_activationinstancelog_rulebookprocesslog_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rulebookprocess",
            name="parent_fqcn",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rulebookprocess",
            name="parent_id",
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rulebookprocess",
            name="activation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.activation",
            ),
        ),
        migrations.RunPython(
            populate_parent_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
