# Generated by Django 4.2.9 on 2024-01-29 22:53

import django.db.models.deletion
from django.db import migrations, models

import aap_eda.core.enums


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_rename_activationinstance_rulebookprocess_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="credentials",
            field=models.ManyToManyField(
                default=None, related_name="activations", to="core.credential"
            ),
        ),
        migrations.AddField(
            model_name="activation",
            name="system_vault_credential",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.credential",
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="vault_identifier",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="credential_type",
            field=models.TextField(
                choices=[
                    ("Container Registry", "Container Registry"),
                    (
                        "GitHub Personal Access Token",
                        "GitHub Personal Access Token",
                    ),
                    (
                        "GitLab Personal Access Token",
                        "GitLab Personal Access Token",
                    ),
                    ("Vault", "Vault"),
                ],
                default=aap_eda.core.enums.CredentialType["REGISTRY"],
            ),
        ),
    ]
