# Generated by Django 4.2.7 on 2024-01-31 21:31

import django.db.models.deletion
from django.db import migrations, models

from aap_eda.core.utils import get_fully_qualified_name


def populate_parent_fields(apps, schema_editor):
    ActivationRequestQueue = apps.get_model(  # noqa: N806
        "core", "ActivationRequestQueue"
    )
    for instance in ActivationRequestQueue.objects.all():
        if instance.activation is None:
            continue
        if not instance.process_parent_id:
            instance.process_parent_id = instance.activation.id
        if not instance.process_parent_fqcn:
            instance.process_parent_fqcn = get_fully_qualified_name(
                instance.activation,
            )
        instance.save(
            update_fields=["process_parent_id", "process_parent_fqcn"]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_rulebookprocess_parent_fqcn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationrequestqueue",
            name="process_parent_fqcn",
            field=models.TextField(
                default="aap_eda.core.models.activation.Activation"
            ),
        ),
        migrations.AddField(
            model_name="activationrequestqueue",
            name="process_parent_id",
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activationrequestqueue",
            name="activation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.activation",
            ),
        ),
        migrations.RunPython(
            populate_parent_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
