# Generated by Django 3.2.18 on 2023-04-07 14:51

from django.db import migrations, models

import aap_eda.core.enums


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_auto_20230406_1914"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="credential_type",
            field=models.TextField(
                choices=[
                    ("Container Registry", "Container Registry"),
                    (
                        "GitHub Personal Access Token",
                        "GitHub Personal Access Token",
                    ),
                    (
                        "GitLab Personal Access Token",
                        "GitLab Personal Access Token",
                    ),
                ],
                default=aap_eda.core.enums.CredentialType["REGISTRY"],
            ),
        ),
    ]
