# Generated by Django 4.2.7 on 2024-01-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_remove_activation_is_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationrequestqueue",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.source",
            ),
        ),
        migrations.AlterField(
            model_name="activationrequestqueue",
            name="activation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.activation",
            ),
        ),
    ]
