# Generated by Django 3.2.18 on 2023-04-07 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_credential_credential_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activation",
            name="execution_environment",
        ),
        migrations.AddField(
            model_name="activation",
            name="decision_environment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.decisionenvironment",
            ),
        ),
    ]
