# Generated by Django 4.2.7 on 2024-02-07 18:43

import django.db.models.deletion
from django.db import migrations, models

import aap_eda.core.enums


def populate_parent_fields(apps, schema_editor):
    ActivationRequestQueue = apps.get_model(  # noqa: N806
        "core", "ActivationRequestQueue"
    )
    for instance in ActivationRequestQueue.objects.all():
        if instance.activation is None:
            continue
        if not instance.process_parent_id:
            instance.process_parent_id = instance.activation.id
        if not instance.process_parent_type:
            instance.process_parent_type = (
                aap_eda.core.enums.ProcessParentType["ACTIVATION"]
            )
        instance.save(
            update_fields=["process_parent_id", "process_parent_type"]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_rulebookprocess_event_stream_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationrequestqueue",
            name="process_parent_id",
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activationrequestqueue",
            name="process_parent_type",
            field=models.TextField(
                choices=[
                    ("activation", "activation"),
                    ("event_stream", "event_stream"),
                ],
                default=aap_eda.core.enums.ProcessParentType["ACTIVATION"],
            ),
        ),
        migrations.AlterField(
            model_name="activationrequestqueue",
            name="activation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.activation",
            ),
        ),
        migrations.RunPython(
            populate_parent_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
