# Generated by Django 3.2.18 on 2023-03-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_auto_20230407_1933"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="users",
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(related_name="users", to="core.Role"),
        ),
    ]
