# Generated by Django 4.2.7 on 2024-02-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_activationrequestqueue_process_parent_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="resource_type",
            field=models.TextField(
                choices=[
                    ("activation", "activation"),
                    ("activation_instance", "activation_instance"),
                    ("audit_rule", "audit_rule"),
                    ("audit_event", "audit_event"),
                    ("user", "user"),
                    ("project", "project"),
                    ("extra_var", "extra_var"),
                    ("rulebook", "rulebook"),
                    ("role", "role"),
                    ("decision_environment", "decision_environment"),
                    ("credential", "credential"),
                ]
            ),
        ),
        migrations.DeleteModel(
            name="Inventory",
        ),
    ]
