# Generated by Django 4.2.7 on 2024-02-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_permission_resource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventstream",
            name="channel_name",
            field=models.TextField(default=None),
        ),
    ]
