# Generated by Django 4.2.7 on 2024-02-09 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_permission_resource_type_delete_inventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventstream",
            name="listener_args",
        ),
        migrations.RemoveField(
            model_name="eventstream",
            name="uuid",
        ),
        migrations.AddField(
            model_name="activation",
            name="event_streams",
            field=models.ManyToManyField(default=None, to="core.eventstream"),
        ),
        migrations.AddField(
            model_name="eventstream",
            name="channel_name",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="eventstream",
            name="credentials",
            field=models.ManyToManyField(
                default=None,
                related_name="event_streams",
                to="core.credential",
            ),
        ),
        migrations.AddField(
            model_name="eventstream",
            name="system_vault_credential",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.credential",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="resource_type",
            field=models.TextField(
                choices=[
                    ("activation", "activation"),
                    ("activation_instance", "activation_instance"),
                    ("audit_rule", "audit_rule"),
                    ("audit_event", "audit_event"),
                    ("user", "user"),
                    ("project", "project"),
                    ("extra_var", "extra_var"),
                    ("rulebook", "rulebook"),
                    ("role", "role"),
                    ("decision_environment", "decision_environment"),
                    ("credential", "credential"),
                    ("event_stream", "event_stream"),
                ]
            ),
        ),
    ]
