# Generated by Django 3.2.18 on 2023-04-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_initial_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditaction",
            name="rule_fired_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="rule_fired_at",
            field=models.DateTimeField(null=True),
        ),
    ]
