# Generated by Django 3.2.18 on 2023-04-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_initial_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
