# Generated by Django 4.2.7 on 2024-02-02 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_eventstream_channel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rulebookprocess",
            name="activation",
        ),
    ]
