# Generated by Django 3.2.18 on 2023-04-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_auto_20230414_1537"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationinstance",
            name="name",
            field=models.TextField(default=""),
        ),
    ]
