# Generated by Django 4.2.7 on 2024-02-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_remove_rulebookprocess_activation"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventstream",
            name="awx_token",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.awxtoken",
            ),
        ),
    ]
