# Generated by Django 4.2.7 on 2024-02-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_eventstream_awx_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="event_streams",
            field=models.ManyToManyField(default=None, to="core.eventstream"),
        ),
    ]
