# Generated by Django 3.2.18 on 2023-04-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_activationinstance_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extravar",
            name="name",
            field=models.TextField(default=None, null=True, unique=True),
        ),
    ]
