# Generated by Django 4.2.7 on 2024-02-19 16:38

from django.db import migrations, models

import aap_eda.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_rename_args_eventstream_source_args"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="log_level",
            field=models.CharField(
                choices=[
                    ("debug", "debug"),
                    ("info", "info"),
                    ("error", "error"),
                ],
                default=aap_eda.core.utils.get_default_log_level,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventstream",
            name="log_level",
            field=models.CharField(
                choices=[
                    ("debug", "debug"),
                    ("info", "info"),
                    ("error", "error"),
                ],
                default=aap_eda.core.utils.get_default_log_level,
                max_length=20,
            ),
        ),
    ]
