# Generated by Django 4.2.7 on 2024-03-04 11:24

import django.db.models.deletion
from django.db import migrations, models


def populate_rulebook_process_queue(apps, schema_editor):
    RulebookProcessQueue = apps.get_model("core", "RulebookProcessQueue")
    RulebookProcess = apps.get_model("core", "RulebookProcess")
    for running_process in RulebookProcess.objects.filter(
        status="RUNNING"
    ).all():
        RulebookProcessQueue.objects.create(
            queue_name="activation",
            process=running_process,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_activation_log_level_eventstream_log_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="RulebookProcessQueue",
            fields=[
                ("queue_name", models.CharField(max_length=255)),
                (
                    "process",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.rulebookprocess",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["queue_name"],
                        name="core_rulebo_queue_n_b7b007_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(
            populate_rulebook_process_queue,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
