# Generated by Django 4.2.11 on 2024-03-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_activation_log_level_eventstream_log_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="rulebookprocess",
            name="worker",
            field=models.TextField(default=None, null=True),
        ),
    ]
