# Generated by Django 3.2.18 on 2023-04-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_alter_extravar_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditrule",
            name="ruleset_name",
            field=models.TextField(null=True),
        ),
    ]
