# Generated by Django 4.2.7 on 2024-02-06 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_activation_event_streams"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventstream",
            name="listener_args",
        ),
        migrations.RemoveField(
            model_name="eventstream",
            name="uuid",
        ),
    ]
