# Generated by Django 4.2.7 on 2024-02-04 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0026_activation_event_streams"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rulebookprocess",
            name="parent_fqcn",
        ),
        migrations.RemoveField(
            model_name="rulebookprocess",
            name="parent_id",
        ),
        migrations.AddField(
            model_name="rulebookprocess",
            name="content_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rulebookprocess",
            name="object_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
