# Generated by Django 3.2.18 on 2023-04-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_alter_extravar_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
