# Generated by Django 3.2.18 on 2023-04-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_auditrule_ruleset_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
