# Generated by Django 4.2.7 on 2024-02-06 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_remove_eventstream_listener_args_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventstream",
            name="awx_token",
        ),
    ]
