# Generated by Django 4.2.7 on 2024-03-05 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_credential_scm_ssh_key_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="credential",
            name="ck_scm_credential",
        ),
    ]
