# Generated by Django 4.2.7 on 2024-03-26 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0027_credentialtype_alter_permission_resource_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activation",
            name="credentials",
        ),
        migrations.RemoveField(
            model_name="activation",
            name="system_vault_credential",
        ),
        migrations.RemoveField(
            model_name="eventstream",
            name="credentials",
        ),
        migrations.RemoveField(
            model_name="eventstream",
            name="system_vault_credential",
        ),
    ]
