# Generated by Django 3.2.18 on 2023-04-19 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_user_modified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activation",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.project",
            ),
        ),
        migrations.AlterField(
            model_name="activation",
            name="rulebook",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.rulebook",
            ),
        ),
    ]
