# Generated by Django 4.2.7 on 2024-03-29 19:18

import django.db.models.deletion
from django.db import migrations, models

import aap_eda.core.enums


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_remove_activation_credentials_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(default="")),
                ("hostname", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("status_message", models.TextField(default=None, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("active", "active"),
                            ("not_responding", "not_responding"),
                            ("abandoned", "abandoned"),
                        ],
                        default=aap_eda.core.enums.NodeStatusType["ACTIVE"],
                    ),
                ),
            ],
            options={
                "db_table": "core_node",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="activationrequestqueue",
            name="request",
            field=models.TextField(
                choices=[
                    ("start", "start"),
                    ("stop", "stop"),
                    ("restart", "restart"),
                    ("delete", "delete"),
                    ("auto_start", "auto_start"),
                    ("monitor", "monitor"),
                    ("node_failover", "node_failover"),
                ]
            ),
        ),
        migrations.AddField(
            model_name="rulebookprocess",
            name="node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="node",
                to="core.node",
            ),
        ),
    ]
