# Generated by Django 4.2.7 on 2024-03-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_remove_activation_credentials_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rulebookprocess",
            name="queue",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="activationrequestqueue",
            name="request",
            field=models.TextField(
                choices=[
                    ("start", "start"),
                    ("stop", "stop"),
                    ("restart", "restart"),
                    ("delete", "delete"),
                    ("auto_start", "auto_start"),
                    ("monitor", "monitor"),
                ]
            ),
        ),
    ]
