# Generated by Django 4.2.7 on 2024-03-26 14:14

from django.db import migrations, models

import aap_eda.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_remove_activation_credentials_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="k8s_service_name",
            field=models.TextField(
                default=aap_eda.core.utils.get_default_k8s_service_name,
                help_text="Name of the kubernetes service",
            ),
        ),
        migrations.AddField(
            model_name="eventstream",
            name="k8s_service_name",
            field=models.TextField(
                default=aap_eda.core.utils.get_default_k8s_service_name,
                help_text="Name of the kubernetes service",
            ),
        ),
    ]
