# Generated by Django 4.2.7 on 2024-02-13 18:11

from django.db import migrations, models

from aap_eda.core.migrations._dab_rbac import (
    create_permissions_as_operation,
    migrate_roles_to_dab,
    remove_dab_models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0028_add_default_organization"),
        ("dab_rbac", "__first__"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activation",
            options={
                "default_permissions": ["add", "view", "delete"],
                "ordering": ("-created_at",),
                "permissions": [
                    ("enable_activation", "Can enable an activation"),
                    ("disable_activation", "Can disable an activation"),
                    ("restart_activation", "Can restart an activation"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="auditrule",
            options={
                "default_permissions": ("view",),
                "ordering": ("-fired_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="extravar",
            options={"default_permissions": ("add", "view")},
        ),
        migrations.AlterModelOptions(
            name="rulebook",
            options={"default_permissions": ("view",)},
        ),
        migrations.AlterModelOptions(
            name="rulebookprocess",
            options={
                "default_permissions": ("view", "delete"),
                "ordering": ("-started_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "default_permissions": ("change", "delete", "view"),
                "permissions": [
                    (
                        "member_organization",
                        "Basic participation permissions for organization",
                    )
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ("organization__name", "name"),
                "permissions": [
                    ("member_team", "Inherit all roles assigned to this team")
                ],
            },
        ),
        migrations.RunPython(
            create_permissions_as_operation, migrations.RunPython.noop
        ),
        migrations.RunPython(migrate_roles_to_dab, remove_dab_models),
        # Temporary - allow creating a user without providing role
        # as long as this relationship refers to the old, now unused, roles
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="core.role"
            ),
        ),
    ]
