# Generated by Django 4.2.7 on 2024-04-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_remove_activation_credentials_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="proxy",
            field=models.TextField(blank=True, default=""),
        ),
    ]
