# Generated by Django 4.2.7 on 2024-04-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_project_proxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="k8s_service_name",
            field=models.TextField(
                default=None,
                help_text="Name of the kubernetes service",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventstream",
            name="k8s_service_name",
            field=models.TextField(
                default=None,
                help_text="Name of the kubernetes service",
                null=True,
            ),
        ),
    ]
