# Generated by Django 3.2.18 on 2023-04-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_auto_20230419_2026"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="rulebook_rulesets",
            field=models.TextField(
                default="", help_text="Content of the last referenced rulebook"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activation",
            name="rulebook_name",
            field=models.TextField(
                default="", help_text="Name of the referenced rulebook"
            ),
            preserve_default=False,
        ),
    ]
