# Generated by Django 3.2.18 on 2023-04-25 15:09

import aap_eda.core.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_activation_decision_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationinstance',
            name='status',
            field=models.TextField(choices=[('starting', 'starting'), ('running', 'running'), ('pending', 'pending'), ('failed', 'failed'), ('stopped', 'stopped'), ('completed', 'completed')], default=aap_eda.core.enums.ActivationStatus['PENDING']),
        ),
    ]
