# Generated by Django 3.2.18 on 2023-04-21 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_alter_activationinstance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="credential",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.credential",
            ),
        ),
    ]
