# Generated by Django 3.2.18 on 2023-04-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_project_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationinstance",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
