# Generated by Django 3.2.18 on 2023-04-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_project_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.user",
            ),
            preserve_default=False,
        ),
    ]
