# Generated by Django 4.2.7 on 2024-04-09 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_dab_rbac"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="permissions",
        ),
        migrations.RemoveField(
            model_name="user",
            name="roles",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
