# Generated by Django 4.2.7 on 2024-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_activation_extra_var_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activation",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="activation",
            name="extra_var",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activation",
            name="k8s_service_name",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Name of the kubernetes service",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventstream",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="eventstream",
            name="extra_var",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventstream",
            name="k8s_service_name",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Name of the kubernetes service",
                null=True,
            ),
        ),
    ]
