# Generated by Django 3.2.18 on 2023-05-08 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_remove_rulebook_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activation",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="activationinstance",
            options={"ordering": ("-started_at",)},
        ),
    ]
