# Generated by Django 4.2.7 on 2024-05-28 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_project_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rulebookprocesslog",
            name="line_number",
        ),
    ]
