# Generated by Django 3.2.18 on 2023-05-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_activation_ruleset_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationinstance",
            name="activation_pod_id",
            field=models.TextField(null=True),
        ),
    ]
