# Generated by Django 4.2.7 on 2024-07-27 19:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import aap_eda.core.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_remove_rulebookprocesslog_line_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="credentialtype",
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="activation",
            name="swap_single_source",
            field=models.BooleanField(
                default=False,
                help_text="Allow swapping of single sources in a rulebook without name match",
            ),
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="The name of the webhook", unique=True
                    ),
                ),
                (
                    "webhook_type",
                    models.TextField(
                        default="hmac",
                        help_text="The type of the webhook based on credential type",
                    ),
                ),
                (
                    "additional_data_headers",
                    models.TextField(
                        blank=True,
                        help_text="The additional http headers which will be added to the event data. The headers are comma delimited",
                    ),
                ),
                (
                    "test_mode",
                    models.BooleanField(
                        default=False, help_text="Enable test mode"
                    ),
                ),
                (
                    "test_content_type",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The content type of test data, when in test mode",
                    ),
                ),
                (
                    "test_content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The content recieved, when in test mode, stored as a yaml string",
                    ),
                ),
                (
                    "test_headers",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The headers recieved, when in test mode, stored as a yaml string",
                    ),
                ),
                (
                    "test_error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The error message,  when in test mode",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "url",
                    models.TextField(
                        help_text="The URL which will be used to post the data to the webhook"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "events_received",
                    models.BigIntegerField(
                        default=0,
                        help_text="The total number of events received by webhook",
                    ),
                ),
                (
                    "last_event_received_at",
                    models.DateTimeField(
                        help_text="The date/time when the last event was received",
                        null=True,
                    ),
                ),
                (
                    "eda_credential",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.edacredential",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=aap_eda.core.models.utils.get_default_organization_id,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who created the webhook",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_webhook",
            },
        ),
        migrations.AddField(
            model_name="activation",
            name="webhooks",
            field=models.ManyToManyField(default=None, to="core.webhook"),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(fields=["id"], name="ix_webhook_id"),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(fields=["name"], name="ix_webhook_name"),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(fields=["uuid"], name="ix_webhook_uuid"),
        ),
    ]
