# Generated by Django 4.2.7 on 2024-08-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_alter_credentialtype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activation",
            name="webhooks",
            field=models.ManyToManyField(
                default=None, related_name="activations", to="core.webhook"
            ),
        ),
    ]
