# Generated by Django 3.2.18 on 2023-05-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_alter_activationinstance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationinstance",
            name="activation_pod_id",
            field=models.TextField(null=True),
        ),
    ]
