# Generated by Django 3.2.18 on 2023-05-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_alter_activationinstance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditrule",
            name="activation_instance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.activationinstance",
            ),
        ),
        migrations.AlterField(
            model_name="auditrule",
            name="job_instance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.jobinstance",
            ),
        ),
    ]
