# Generated by Django 3.2.18 on 2023-05-19 13:45

from django.db import migrations, models

import aap_eda.core.enums


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_activationinstance_activation_pod_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="failure_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activation",
            name="is_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activationinstance",
            name="status",
            field=models.TextField(
                choices=[
                    ("starting", "starting"),
                    ("running", "running"),
                    ("pending", "pending"),
                    ("failed", "failed"),
                    ("stopping", "stopping"),
                    ("stopped", "stopped"),
                    ("completed", "completed"),
                    ("unresponsive", "unresponsive"),
                ],
                default=aap_eda.core.enums.ActivationStatus["PENDING"],
            ),
        ),
    ]
