# Generated by Django 4.2.7 on 2024-08-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_remove_credentialtype_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activation",
            name="webhooks",
            field=models.ManyToManyField(
                default=None, related_name="activations", to="core.webhook"
            ),
        ),
    ]
