# Generated by Django 4.2.7 on 2024-08-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_alter_activation_webhooks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activation",
            name="swap_single_source",
        ),
        migrations.AddField(
            model_name="activation",
            name="source_mappings",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Mapping between sources and event streams",
            ),
        ),
    ]
