# Generated by Django 4.2.7 on 2024-08-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_remove_activation_swap_single_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="skip_audit_events",
            field=models.BooleanField(
                default=False, help_text="Skip audit events for activation"
            ),
        ),
    ]
