# Generated by Django 4.2.7 on 2024-08-14 18:15

import django.db.models.deletion
from django.db import migrations, models

import aap_eda.core.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_activation_skip_audit_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activation",
            name="organization",
            field=models.ForeignKey(
                default=aap_eda.core.models.utils.get_default_organization_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="auditrule",
            name="organization",
            field=models.ForeignKey(
                default=aap_eda.core.models.utils.get_default_organization_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="decisionenvironment",
            name="organization",
            field=models.ForeignKey(
                default=aap_eda.core.models.utils.get_default_organization_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="edacredential",
            name="organization",
            field=models.ForeignKey(
                default=aap_eda.core.models.utils.get_default_organization_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                default=aap_eda.core.models.utils.get_default_organization_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="rulebook",
            name="organization",
            field=models.ForeignKey(
                default=aap_eda.core.models.utils.get_default_organization_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="rulebookprocess",
            name="organization",
            field=models.ForeignKey(
                default=aap_eda.core.models.utils.get_default_organization_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="organization",
            field=models.ForeignKey(
                default=aap_eda.core.models.utils.get_default_organization_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
    ]
