# Generated by Django 4.2.7 on 2024-08-19 19:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import aap_eda.core.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_remove_activation_event_streams_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="The name of the webhook", unique=True
                    ),
                ),
                (
                    "event_stream_type",
                    models.TextField(
                        default="hmac",
                        help_text="The type of the event stream based on credential type",
                    ),
                ),
                (
                    "additional_data_headers",
                    models.TextField(
                        blank=True,
                        help_text="The additional http headers which will be added to the event data. The headers are comma delimited",
                    ),
                ),
                (
                    "test_mode",
                    models.BooleanField(
                        default=False, help_text="Enable test mode"
                    ),
                ),
                (
                    "test_content_type",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The content type of test data, when in test mode",
                    ),
                ),
                (
                    "test_content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The content recieved, when in test mode, stored as a yaml string",
                    ),
                ),
                (
                    "test_headers",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The headers recieved, when in test mode, stored as a yaml string",
                    ),
                ),
                (
                    "test_error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The error message,  when in test mode",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "url",
                    models.TextField(
                        help_text="The URL which will be used to post to the event stream"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "events_received",
                    models.BigIntegerField(
                        default=0,
                        help_text="The total number of events received by event stream",
                    ),
                ),
                (
                    "last_event_received_at",
                    models.DateTimeField(
                        help_text="The date/time when the last event was received",
                        null=True,
                    ),
                ),
                (
                    "eda_credential",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.edacredential",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=aap_eda.core.models.utils.get_default_organization_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who created the webhook",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="activation",
            name="webhooks",
        ),
        migrations.DeleteModel(
            name="Webhook",
        ),
        migrations.AddField(
            model_name="activation",
            name="event_streams",
            field=models.ManyToManyField(
                default=None, related_name="activations", to="core.eventstream"
            ),
        ),
    ]
