# Generated by Django 4.2.7 on 2024-08-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_eventstream_remove_activation_webhooks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventstream",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
