# Generated by Django 4.2.7 on 2024-10-11 14:49

from django.db import migrations

from aap_eda.core import enums
from aap_eda.core.management.commands.create_initial_data import (
    NEW_HELP_TEXT,
    ORIG_HELP_TEXT,
)


def update_credential_type(apps, schema_editor):
    _update_credential_type_help_text(apps, NEW_HELP_TEXT)


def backward_credential_type(apps, schema_editor):
    _update_credential_type_help_text(apps, ORIG_HELP_TEXT)


def _update_credential_type_help_text(apps, help_text):
    credential_type = apps.get_model("core", "CredentialType")  # noqa: N806

    for ctype in credential_type.objects.filter(
        name=enums.DefaultCredentialType.AAP
    ):
        for field in ctype.inputs["fields"]:
            if field["id"] == "host":
                field["help_text"] = help_text

        ctype.save(update_fields=["inputs"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_setting"),
    ]

    operations = [
        migrations.RunPython(update_credential_type, backward_credential_type),
    ]
