# Generated by Django 4.2.7 on 2024-10-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_setting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationrequestqueue",
            name="request",
            field=models.TextField(
                choices=[
                    ("start", "start"),
                    ("running", "running"),
                    ("stop", "stop"),
                    ("restart", "restart"),
                    ("delete", "delete"),
                    ("auto_start", "auto_start"),
                ]
            ),
        ),
    ]
