# Generated by Django 4.2.7 on 2024-10-22 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_alter_activation_organization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventstream",
            name="url",
        ),
    ]
