# Generated by Django 4.2.16 on 2024-11-22 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_remove_eventstream_url"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ruleset",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="ruleset",
            name="rulebook",
        ),
        migrations.DeleteModel(
            name="Rule",
        ),
        migrations.DeleteModel(
            name="Ruleset",
        ),
    ]
