# Generated by Django 4.2.16 on 2024-11-26 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_alter_ruleset_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date/time this resource was created.",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="The user who created this resource.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="modified",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date/time this resource was created.",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="modified_by",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="The user who last modified this resource.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modified+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                help_text="The name of this resource.",
                max_length=512,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date/time this resource was created.",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="The user who created this resource.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="modified",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date/time this resource was created.",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="modified_by",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="The user who last modified this resource.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modified+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(
                help_text="The name of this resource.", max_length=512
            ),
        ),
    ]
