# Generated by Django 4.2.16 on 2025-01-06 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_activation_created_by_activation_modified_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activation",
            options={
                "default_permissions": ["add", "view", "change", "delete"],
                "ordering": ("-created_at",),
                "permissions": [
                    ("enable_activation", "Can enable an activation"),
                    ("disable_activation", "Can disable an activation"),
                    ("restart_activation", "Can restart an activation"),
                ],
            },
        ),
    ]
