# Generated by Django 4.2.16 on 2025-02-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_activation_edited_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="request_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="rulebookprocess",
            name="request_id",
            field=models.TextField(null=True),
        ),
    ]
