# Generated by Django 4.2.16 on 2025-02-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_activation_edited_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="log_tracking_id",
            field=models.TextField(blank=True),
        ),
    ]
