# Generated by Django 4.2.16 on 2025-03-06 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_activation_edited_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activation",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="eventstream",
            name="owner",
            field=models.ForeignKey(
                help_text="The user who created the webhook",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
