# Generated by Django 4.2.16 on 2025-03-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_alter_activation_user_alter_eventstream_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationrequestqueue",
            name="x_request_id",
            field=models.UUIDField(
                default="00000000-0000-0000-0000-000000000000",
                editable=False,
                null=True,
                unique=True,
            ),
        ),
    ]
