# Generated by Django 4.2.16 on 2025-03-11 01:31

import uuid

from django.db import migrations, models


def set_log_tracking_id(apps, schema_editor):
    activation_model = apps.get_model("core", "Activation")  # noqa: N806
    for obj in activation_model.objects.all():
        obj.log_tracking_id = str(uuid.uuid4())
        obj.save(update_fields=["log_tracking_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_activation_edited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="log_tracking_id",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="activationrequestqueue",
            name="request_id",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(
            set_log_tracking_id,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
