# Generated by Django 4.2.16 on 2025-04-07 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_setting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decisionenvironment",
            name="credential",
        ),
        migrations.RemoveField(
            model_name="project",
            name="credential",
        ),
        migrations.DeleteModel(
            name="Credential",
        ),
    ]
