# Generated by Django 4.2.23 on 2025-07-14 20:33

import logging

from django.db import migrations


logger = logging.getLogger(__name__)


def rename_roles(apps, schema_editor):
    RoleDefinition = apps.get_model("dab_rbac", "RoleDefinition")

    rename_map = {
        "Project Admin": "EDA Project Admin",
        "Project Use": "EDA Project Use",
    }

    for old_name, new_name in rename_map.items():
        try:
            role = RoleDefinition.objects.get(name=old_name)
            role.name = new_name
            role.save(update_fields=["name"])
            logger.info(f'Renamed role from migration from {old_name} to {new_name}')
        except RoleDefinition.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_remove_decisionenvironment_credential_and_more"),
    ]

    operations = [
        migrations.RunPython(rename_roles, migrations.RunPython.noop),
    ]

