# Generated by Django 4.2.16 on 2025-06-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_remove_decisionenvironment_credential_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationrequestqueue",
            name="request",
            field=models.TextField(
                choices=[
                    ("start", "start"),
                    ("stop", "stop"),
                    ("restart", "restart"),
                    ("delete", "delete"),
                    ("disable", "disable"),
                    ("auto_start", "auto_start"),
                ]
            ),
        ),
    ]
