# Generated by Django 4.2.23 on 2025-07-21 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import aap_eda.core.utils.crypto.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_rename_project_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialInputSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("input_field_name", models.CharField(max_length=1024)),
                (
                    "metadata",
                    aap_eda.core.utils.crypto.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%s(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%s(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "source_credential",
                    models.ForeignKey(
                        help_text="External credential",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_input_sources",
                        to="core.edacredential",
                    ),
                ),
                (
                    "target_credential",
                    models.ForeignKey(
                        help_text="Non external credential",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_sources",
                        to="core.edacredential",
                    ),
                ),
            ],
            options={
                "db_table": "core_credential_input_source",
                "ordering": (
                    "target_credential",
                    "source_credential",
                    "input_field_name",
                ),
                "unique_together": {("target_credential", "input_field_name")},
            },
        ),
    ]
