# Generated by Django 4.2.23 on 2025-07-29 10:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_credentialinputsource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventstream",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
