# Generated by Django 4.2.23 on 2025-08-12 13:36

from django.db import migrations, models

import aap_eda.core.enums


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_add_unique_uuid_to_event_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionenvironment",
            name="pull_policy",
            field=models.CharField(
                choices=[
                    ("Always", "Always"),
                    ("Never", "Never"),
                    ("IfNotPresent", "IfNotPresent"),
                ],
                default=aap_eda.core.enums.ImagePullPolicy["ALWAYS"],
                help_text="Pull policy for the image before running",
                max_length=16,
            ),
        ),
    ]
