# Generated by Django 4.2.23 on 2025-08-18 14:14

from django.db import migrations, models

import aap_eda.core.enums


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_add_unique_uuid_to_event_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionenvironment",
            name="pull_policy",
            field=models.CharField(
                choices=[
                    ("always", "Always pull container before running."),
                    (
                        "missing",
                        "Only pull the image if not present before running.",
                    ),
                    ("never", "Never pull container before running."),
                ],
                default=aap_eda.core.enums.ImagePullPolicy.ALWAYS,
                help_text="Pull policy for the image before running",
                max_length=16,
            ),
        ),
    ]
