# Generated by Django 5.2.9 on 2026-01-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_decisionenvironment_pull_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Timestamp of the last successful project sync",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="scm_update_cache_timeout",
            field=models.IntegerField(
                default=0,
                help_text="Cache timeout in seconds for project updates (0 = always update, max 86400)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="update_revision_on_launch",
            field=models.BooleanField(
                default=False,
                help_text="Enable automatic project sync on activation launch",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scm_update_cache_timeout__range", (0, 86400))
                ),
                name="ck_cache_timeout_range",
            ),
        ),
    ]
