# Generated by Django 5.2.9 on 2026-01-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_decisionenvironment_pull_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_synced_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="scm_update_cache_timeout",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="scm_update_on_launch",
            field=models.BooleanField(default=False),
        ),
    ]
