# Generated by Django 5.2.9 on 2026-03-25 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_activation_restart_and_sync_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="enable_persistence",
            field=models.BooleanField(
                default=False, help_text="Enable persistence for activation"
            ),
        ),
        migrations.AddField(
            model_name="activation",
            name="rule_engine_credential",
            field=models.ForeignKey(
                default=None,
                help_text="The Rule Engine Credential to use, if empty use the default system rule engine credential.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.edacredential",
            ),
        ),
    ]
