# Generated by Django on 2026-04-13 00:00

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def rename_eda_credential_roles_forward(apps, schema_editor):
    """
    Rename existing EDA Credential-related roles to use proper "EDA" casing.

    This function handles the forward migration by renaming existing
    EDA Credential roles to use proper "EDA" capitalization instead of "Eda".
    """
    RoleDefinition = apps.get_model("dab_rbac", "RoleDefinition")  # noqa: N806

    role_mappings = {
        "Eda Credential Admin": "EDA Credential Admin",
        "Eda Credential Use": "EDA Credential Use",
        "Organization Eda Credential Admin": "Organization EDA Credential Admin",
    }

    for old_name, new_name in role_mappings.items():
        try:
            old_role = RoleDefinition.objects.get(name=old_name)
            new_role_exists = RoleDefinition.objects.filter(
                name=new_name
            ).exists()

            if not new_role_exists:
                old_role.name = new_name
                old_role.save()
                logger.info(f"Renamed role '{old_name}' to '{new_name}'")
            else:
                logger.warning(
                    f"Role '{new_name}' already exists, skipping rename of '{old_name}'"
                )

        except RoleDefinition.DoesNotExist:
            logger.info(f"Role '{old_name}' not found, skipping rename")


def rename_eda_credential_roles_reverse(apps, schema_editor):
    """Reverse the role renaming in case of rollback."""
    RoleDefinition = apps.get_model("dab_rbac", "RoleDefinition")  # noqa: N806

    role_mappings = {
        "EDA Credential Admin": "Eda Credential Admin",
        "EDA Credential Use": "Eda Credential Use",
        "Organization EDA Credential Admin": "Organization Eda Credential Admin",
    }

    for old_name, new_name in role_mappings.items():
        try:
            old_role = RoleDefinition.objects.get(name=old_name)
            new_role_exists = RoleDefinition.objects.filter(
                name=new_name
            ).exists()

            if not new_role_exists:
                old_role.name = new_name
                old_role.save()
                logger.info(f"Reverted role '{old_name}' to '{new_name}'")
            else:
                logger.warning(
                    f"Role '{new_name}' already exists, skipping revert of '{old_name}'"
                )

        except RoleDefinition.DoesNotExist:
            logger.info(f"Role '{old_name}' not found, skipping revert")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_activation_enable_persistence_and_more"),
        ("dab_rbac", "0008_remote_permissions_cleanup"),
    ]

    operations = [
        migrations.RunPython(
            rename_eda_credential_roles_forward,
            rename_eda_credential_roles_reverse,
        ),
    ]
