# Generated by Django 5.2.13 on 2026-04-21 18:49

import django.db.models.deletion
from django.db import migrations, models

import aap_eda.core.enums


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_activation_enable_persistence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "job_type",
                    models.TextField(
                        choices=[
                            ("cleanup_audit_logs", "cleanup_audit_logs"),
                            (
                                "cleanup_stale_activations",
                                "cleanup_stale_activations",
                            ),
                        ],
                        default=aap_eda.core.enums.ManagementJobType[
                            "CLEANUP_AUDIT_LOGS"
                        ],
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "core_management_job",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ManagementJobExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default=aap_eda.core.enums.ExecutionStatus["PENDING"],
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("output", models.TextField(blank=True, default="")),
                ("errors", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "management_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="core.managementjob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "core_management_job_execution",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="ManagementJobSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule", models.TextField(help_text="Cron expression")),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "management_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="core.managementjob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "core_management_job_schedule",
                "ordering": ("-next_run_at",),
            },
        ),
    ]
