# Generated by Django 5.2.9 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_activation_enable_persistence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="k8s_pod_annotations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Annotations on activation job pod template metadata.",
            ),
        ),
        migrations.AddField(
            model_name="activation",
            name="k8s_pod_labels",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Additional labels merged into activation job pod "
                    "template metadata."
                ),
            ),
        ),
        migrations.AddField(
            model_name="activation",
            name="k8s_pod_service_account_name",
            field=models.TextField(
                blank=True,
                default=None,
                help_text=(
                    "Kubernetes ServiceAccount name for activation job pods "
                    "(Kubernetes-style deployments only)."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activation",
            name="k8s_pod_node_selector",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Kubernetes nodeSelector applied to activation job "
                    "pods for scheduling onto specific nodes."
                ),
            ),
        ),
    ]
