# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_activation_k8s_pod_tolerations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventStreamSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%s(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%s(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_stream_setting",
                        to="core.organization",
                    ),
                ),
                (
                    "allowed_ips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text=(
                            "IP allowlist. Accepts individual IPs "
                            "and CIDR ranges (e.g. 192.30.252.0/22). "
                            "When non-empty, only matching IPs may "
                            "post events. Empty means all IPs are "
                            "allowed."
                        ),
                    ),
                ),
                (
                    "blocked_ips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text=(
                            "IPs that attempted access and were "
                            "rejected. Auto-populated on failed "
                            "requests for admin visibility."
                        ),
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True),
                ),
            ],
            options={
                "db_table": "core_event_stream_setting",
                "ordering": ("-created_at",),
                "default_permissions": ("add", "change", "view"),
            },
        ),
    ]
