# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_activation_k8s_pod_tolerations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventStreamSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_stream_setting",
                        to="core.organization",
                    ),
                ),
                (
                    "allowed_ips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text=(
                            "IP allowlist. When non-empty, only these IPs "
                            "may post events to any event stream in this "
                            "organization."
                        ),
                    ),
                ),
                (
                    "blocked_ips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text=(
                            "Admin-managed list of permanently blocked IPs."
                        ),
                    ),
                ),
                (
                    "blacklist_threshold",
                    models.PositiveIntegerField(
                        default=5,
                        help_text=(
                            "Number of auth failures before an IP is "
                            "auto-blacklisted. Set to 0 to disable "
                            "auto-blacklisting."
                        ),
                    ),
                ),
                (
                    "blacklist_window",
                    models.PositiveIntegerField(
                        default=60,
                        help_text=(
                            "Seconds within which failures are counted."
                        ),
                    ),
                ),
                (
                    "lockout_duration",
                    models.PositiveIntegerField(
                        default=3600,
                        help_text=(
                            "Seconds an auto-blacklisted IP stays blocked."
                        ),
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True),
                ),
            ],
            options={
                "db_table": "core_event_stream_setting",
                "ordering": ("-created_at",),
            },
        ),
    ]
