# Generated by Django 5.2.9 on 2026-09-16 19:20

from django.db import migrations, models
from django.db.models import Value
from django.db.models.functions import Cast, Concat


def backfill_rulebook_process_names(apps, schema_editor):
    """Assign a deterministic name to blank RulebookProcess.name rows."""
    RulebookProcess = apps.get_model("core", "RulebookProcess")  # noqa: N806
    db_alias = schema_editor.connection.alias
    RulebookProcess.objects.using(db_alias).filter(name="").update(
        name=Concat(
            Value("process_"), Cast("pk", output_field=models.CharField())
        )
    )


def backfill_job_instance_names(apps, schema_editor):
    """Assign a deterministic name to JobInstance rows with a blank name."""
    JobInstance = apps.get_model("core", "JobInstance")  # noqa: N806
    db_alias = schema_editor.connection.alias
    JobInstance.objects.using(db_alias).filter(name="").update(
        name=Concat(Value("job_"), Cast("pk", output_field=models.CharField()))
    )


def backfill_event_stream_names(apps, schema_editor):
    """Assign a deterministic name to EventStream rows with a blank name."""
    EventStream = apps.get_model("core", "EventStream")  # noqa: N806
    db_alias = schema_editor.connection.alias
    EventStream.objects.using(db_alias).filter(name="").update(
        name=Concat(
            Value("event_stream_"), Cast("pk", output_field=models.CharField())
        )
    )


def backfill_awx_token_names(apps, schema_editor):
    """Assign a deterministic name to AWXToken rows with a blank name."""
    AWXToken = apps.get_model("core", "AWXToken")  # noqa: N806
    db_alias = schema_editor.connection.alias
    AWXToken.objects.using(db_alias).filter(name="").update(
        name=Concat(
            Value("awx_token_"), Cast("pk", output_field=models.CharField())
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_activation_k8s_pod_tolerations"),
    ]

    operations = [
        migrations.RunPython(
            backfill_rulebook_process_names, migrations.RunPython.noop
        ),
        migrations.RunPython(
            backfill_job_instance_names, migrations.RunPython.noop
        ),
        migrations.RunPython(
            backfill_event_stream_names, migrations.RunPython.noop
        ),
        migrations.RunPython(
            backfill_awx_token_names, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="awxtoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="ck_awx_token_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventstream",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="ck_event_stream_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobinstance",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="ck_job_instance_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulebookprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="ck_rulebook_process_name_not_empty",
            ),
        ),
    ]
