# Generated by Django 5.2.9 on 2026-08-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_awxtoken_ck_awx_token_name_not_empty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="store_debug_logs",
            field=models.BooleanField(
                default=False,
                help_text="When false (default), DEBUG-level log lines are sent to container stdout but not stored in the database.",
            ),
        ),
    ]
