# Generated by Django 5.2.9 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_activation_store_debug_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="rulebookprocess",
            name="stored_lines_since_cap_check",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="rulebookprocesslog",
            index=models.Index(
                fields=["activation_instance", "id"],
                name="ix_process_log_instance_id",
            ),
        ),
    ]
