---
name: Release eda-server

env:
  LC_ALL: "C.UTF-8" # prevent ERROR: Ansible could not initialize the preferred locale: unsupported locale setting

on:
  workflow_dispatch:

jobs:
  stage:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      packages: write
      contents: write
    steps:
      - name: Install go-task
        run: |
          curl -sL https://taskfile.dev/install.sh | sh
          mv ./bin/task /usr/local/bin/task
          task --version

      - name: Checkout eda-server
        uses: actions/checkout@v3

      - name: Get python version from Taskfile
        run: echo py_version=`task PYTHON_VERSION` >> $GITHUB_ENV

      - name: Install python ${{ env.py_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.py_version }}

      - name: Install python deeps
        run: pip install -r requirements_dev.txt

      - name: Create release
        run: ansible-playbook tools/ansible/release.yml -i localhost -e github_token=${{ secrets.GITHUB_TOKEN }}
